### ISSUE TITLE
Demos not working

### ISSUE THREAD

**Issue by sk-** [jamt9000/webcv#2]
The demos linked in the Readme do not work. I get a couldn't get webcam popup, even though my camera works perfectly with webrtc. If I run the examples locally, there's an error in the js console saying that a stream could not be loaded.

**Comment by jamt9000** [comment]
Fixed, it was due to a browser api change https://www.fxsitecompat.com/en-CA/docs/2017/url-createobjecturl-stream-has-been-deprecated/
